#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

echo "* Setup redis-requirements"
mv /var/zoneinit/tmp/sentinel.conf /opt/local/etc/sentinel.conf
chown redis:redis /opt/local/etc/redis.conf
chown redis:redis /opt/local/etc/sentinel.conf
chmod 0640 /opt/local/etc/sentinel.conf
mkdir -p /opt/local/etc/tls/
chown redis:redis /opt/local/etc/tls/
chmod 0750 /opt/local/etc/tls/
gem install redis

echo "* import sentinel smf manifest"
svccfg import /opt/local/lib/svc/manifest/sentinel.xml

echo "* Cleaning up"
rm /root/customize
cp /etc/skel/.bashrc /root/.bashrc
rm -rf /var/zoneinit/tmp
mkdir -p /nonexistent

sm-prepare-image -y
